//
// Created by ancalagorn on 13.05.2026.
//

#include "Exporter.h"

#include <sstream>
#include <iomanip>
#include <cmath>

#include <imgui.h>

std::string GenerateThemeCode(const ImGuiStyle& style, const ExportOptions& opts) {
    // Baselines for "only changed" comparison.
    // Default-constructed ImGuiStyle holds the canonical default float values.
    // StyleColorsDark sets the Dark palette — compare colors against that.
    ImGuiStyle floatBaseline;
    ImGuiStyle colorBaseline;
    ImGui::StyleColorsDark(&colorBaseline);

    const int prec = opts.floatPrecision;
    const bool onlyChanged = opts.onlyChanged;

    // Format a single float with the configured precision and trailing 'f'.
    auto flt = [&](const float v) -> std::string {
        std::ostringstream tmp;
        tmp << std::fixed << std::setprecision(prec) << v << "f";
        return tmp.str();
    };

    auto vec2 = [&](const ImVec2 v) -> std::string {
        return "ImVec2(" + flt(v.x) + ", " + flt(v.y) + ")";
    };

    auto vec4 = [&](const ImVec4 v) -> std::string {
        return "ImVec4(" + flt(v.x) + ", " + flt(v.y) + ", " + flt(v.z) + ", " + flt(v.w) + ")";
    };

    auto eqF = [](const float a, const float b) { return std::fabs(a - b) < 1e-5f; };
    auto eqV2 = [&](const ImVec2 a, const ImVec2 b) { return eqF(a.x, b.x) && eqF(a.y, b.y); };
    auto eqV4 = [&](const ImVec4 a, const ImVec4 b) {
        return eqF(a.x, b.x) && eqF(a.y, b.y) && eqF(a.z, b.z) && eqF(a.w, b.w);
    };

    std::ostringstream ss;

    // ── header ────────────────────────────────────────────────────────────────
    if (opts.includeComments) {
        ss << "// Generated by DearThemeLab\n";
        ss << "// Paste this into your project and call "
           << opts.functionName << "() once after ImGui::CreateContext()\n\n";
    }

    ss << "#include <imgui.h>\n\n";

    const bool hasNS = !opts.namespaceName.empty();
    if (hasNS) ss << "namespace " << opts.namespaceName << " {\n\n";

    ss << "void " << opts.functionName << "()\n{\n";
    ss << "    ImGuiStyle& style = ImGui::GetStyle();\n";

    // ── helper macros (lambdas, actually) ─────────────────────────────────────
    // Emit a float field if it changed (or always if !onlyChanged).
    auto emitF = [&](const char* field, const float val, const float base) {
        if (onlyChanged && eqF(val, base)) return;
        ss << "    style." << field << " = " << flt(val) << ";\n";
    };

    auto emitV2 = [&](const char* field, const ImVec2 val, const ImVec2 base) {
        if (onlyChanged && eqV2(val, base)) return;
        ss << "    style." << field << " = " << vec2(val) << ";\n";
    };

    auto emitB = [&](const char* field, const bool val, const bool base) {
        if (onlyChanged && val == base) return;
        ss << "    style." << field << " = " << (val ? "true" : "false") << ";\n";
    };

    // ── Main ──────────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Main\n";
    emitV2("WindowPadding",     style.WindowPadding,     floatBaseline.WindowPadding);
    emitV2("FramePadding",      style.FramePadding,      floatBaseline.FramePadding);
    emitV2("CellPadding",       style.CellPadding,       floatBaseline.CellPadding);
    emitV2("ItemSpacing",       style.ItemSpacing,        floatBaseline.ItemSpacing);
    emitV2("ItemInnerSpacing",  style.ItemInnerSpacing,   floatBaseline.ItemInnerSpacing);
    emitV2("TouchExtraPadding", style.TouchExtraPadding,  floatBaseline.TouchExtraPadding);
    emitF ("IndentSpacing",     style.IndentSpacing,      floatBaseline.IndentSpacing);
    emitF ("ScrollbarSize",     style.ScrollbarSize,      floatBaseline.ScrollbarSize);
    emitF ("GrabMinSize",       style.GrabMinSize,        floatBaseline.GrabMinSize);

    // ── Borders ───────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Borders\n";
    emitF("WindowBorderSize", style.WindowBorderSize, floatBaseline.WindowBorderSize);
    emitF("ChildBorderSize",  style.ChildBorderSize,  floatBaseline.ChildBorderSize);
    emitF("PopupBorderSize",  style.PopupBorderSize,  floatBaseline.PopupBorderSize);
    emitF("FrameBorderSize",  style.FrameBorderSize,  floatBaseline.FrameBorderSize);
    emitF("TabBorderSize",    style.TabBorderSize,    floatBaseline.TabBorderSize);

    // ── Rounding ──────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Rounding\n";
    emitF("WindowRounding",    style.WindowRounding,    floatBaseline.WindowRounding);
    emitF("ChildRounding",     style.ChildRounding,     floatBaseline.ChildRounding);
    emitF("FrameRounding",     style.FrameRounding,     floatBaseline.FrameRounding);
    emitF("PopupRounding",     style.PopupRounding,     floatBaseline.PopupRounding);
    emitF("ScrollbarRounding", style.ScrollbarRounding, floatBaseline.ScrollbarRounding);
    emitF("GrabRounding",      style.GrabRounding,      floatBaseline.GrabRounding);
    emitF("TabRounding",       style.TabRounding,       floatBaseline.TabRounding);

    // ── Alignment ────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Alignment\n";
    emitV2("WindowTitleAlign",    style.WindowTitleAlign,    floatBaseline.WindowTitleAlign);
    emitV2("ButtonTextAlign",     style.ButtonTextAlign,     floatBaseline.ButtonTextAlign);
    emitV2("SelectableTextAlign", style.SelectableTextAlign, floatBaseline.SelectableTextAlign);

    // WindowMenuButtonPosition: emit as named constant
    {
        bool posChanged = style.WindowMenuButtonPosition != floatBaseline.WindowMenuButtonPosition;
        if (!onlyChanged || posChanged) {
            const char* dirName =
                (style.WindowMenuButtonPosition == ImGuiDir_None)  ? "ImGuiDir_None"  :
                (style.WindowMenuButtonPosition == ImGuiDir_Left)  ? "ImGuiDir_Left"  :
                (style.WindowMenuButtonPosition == ImGuiDir_Right) ? "ImGuiDir_Right" : "ImGuiDir_None";
            ss << "    style.WindowMenuButtonPosition = " << dirName << ";\n";
        }
    }

    // ── Rendering ─────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Rendering\n";
    emitF("Alpha",         style.Alpha,         floatBaseline.Alpha);
    emitF("DisabledAlpha", style.DisabledAlpha, floatBaseline.DisabledAlpha);
    emitB("AntiAliasedLines",       style.AntiAliasedLines,       floatBaseline.AntiAliasedLines);
    emitB("AntiAliasedLinesUseTex", style.AntiAliasedLinesUseTex, floatBaseline.AntiAliasedLinesUseTex);
    emitB("AntiAliasedFill",        style.AntiAliasedFill,        floatBaseline.AntiAliasedFill);

    // ── Colors ────────────────────────────────────────────────────────────────
    if (opts.includeComments) ss << "\n    // Colors\n";
    for (int i = 0; i < ImGuiCol_COUNT; i++) {
        const ImVec4& c  = style.Colors[i];
        const ImVec4& bc = colorBaseline.Colors[i];

        if (onlyChanged && eqV4(c, bc)) continue;

        ss << "    style.Colors[ImGuiCol_" << ImGui::GetStyleColorName(i)
           << "] = " << vec4(c) << ";\n";
    }

    ss << "}\n";

    if (hasNS) ss << "\n} // namespace " << opts.namespaceName << "\n";

    return ss.str();
}
